### ISSUE TITLE
Property 'addScrollListener' does not exist on type 'Content'.

### ISSUE THREAD

**Issue by NBAMj** [lwz7512/ionic2-misin-ctrls#1]
I'm getting this error `Property 'addScrollListener' does not exist on type 'Content'.` in `components/smtimg-ctrlr.ts`
Can you help me with this error ?

I'm using ionic v2 RC5

**Comment by lwz7512** [comment]
@NBAMj thanks for using this project, the problem you mentioned has just updated and fixed based on ionic2 final version, sorry for let you waiting for so much time!
The 'addScrollListener' has removed from latest ionic2 version, now it using 'content.ionScroll' to subscribe the scroll event, so, update your local project then using new version!
